<html>
	<head>
		<script type="text/javascript">
			// Generated by CoffeeScript 1.6.3
		(function() {
			var BrowserManipulation, Vimtastic;

			Vimtastic = (function() {
				function Vimtastic() {
					this.browser = new BrowserManipulation;
					safari.application.addEventListener("message", this.message, false);
					safari.application.addEventListener("activate", this.activate, false);
				}

				Vimtastic.prototype.message = function() {
					var i, tabs, _i, _ref, _results;
					tabs = safari.application.activeBrowserWindow.tabs;
					_results = [];
					for (i = _i = 0, _ref = tabs.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
						_results.push(safari.application.activeBrowserWindow.tabs[i].page.dispatchMessage('setActive', false));
					}
					return _results;
				};

				Vimtastic.prototype.activate = function() {};

				return Vimtastic;

			})();

			BrowserManipulation = (function() {
				function BrowserManipulation() {}

				BrowserManipulation.prototype.activeTabInfo = function() {
					return {
						activeTab: safari.application.activeBrowserWindow.activeTab,
								activeTabIndex: safari.application.activeBrowserWindow.tabs.indexOf(safari.application.activeBrowserWindow.activeTab)
					};
				};

				BrowserManipulation.prototype.changeTab = function(direction) {
					var t, tabs;
					t = this.activeTabInfo();
					tabs = safari.application.activeBrowserWindow.tabs;
					if (direction === "left") {
						if (t.activeTabIndex === 0) {
							return tabs[tabs.length - 1].activate();
						} else {
							return tabs[t.activeTabIndex - 1].activate();
						}
					} else if (direction === "right") {
						if (t.activeTabIndex === tabs.length - 1) {
							return t[0].activate();
						} else {
							return tabs[t.activeTabIndex + 1].activate();
						}
					}
				};

				return BrowserManipulation;

			})();

			window.vimtastic = new Vimtastic;

		}).call(this);
</script>
	</head>
</html>


